# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d860a98a53d4a3bcc66662a9d1ee6f6c0329c60b59d098217a5943224a45a577d2f54f9d71b29c953671091945f27068c2892c5b20e14e8f55cada57049ccb7c

test:
  secret_key_base: e37d603842d30215db0800196be064c87175d57a6245f3c00adc33fc780522359827b10aeca5109ac56e66249a86ee2fcb0b94de9377c427ab8a9dc4ae4dc3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
